# action.yml
name: 'GitNextTag'
description: 'Deterine the next tag for a git repository based on the latest tag from a base tag mask'
author: 'https://github.com/joostvdg'
repo: 'https://github.com/joostvdg/git-next-tag-action'
branding:
  icon: 'tag'
  color: 'orange'
inputs:
  base-tag:
    description: 'Base tag mask to determine the latest tag'
    required: true
    default: '0.1'
  path:
    description: 'Path to the git repository'
    required: true
    default: '.'
outputs:
  next-tag:
    description: 'The next tag for the git repository'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --baseTag
    - ${{ inputs.base-tag }}
    - --path
    - ${{ inputs.path }}
    - --outputPath
    -  ${{ inputs.path }}/version.txt
    - -vvv
